import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { mkdtempSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { ArgsError, parseArgs } from "./format.ts";

describe("parseArgs", () => {
  it("bare invocation → format subcommand", () => {
    expect(parseArgs([])).toEqual({ subcommand: { kind: "format" } });
  });

  it("parses --in, --out, --out-dir", () => {
    expect(parseArgs(["--in", "a.md", "--out", "b.html", "--out-dir", "x"]))
      .toEqual({
        subcommand: { kind: "format" },
        inPath: "a.md",
        outPath: "b.html",
        outDir: "x",
      });
  });

  it("flags help", () => {
    expect(parseArgs(["--help"])).toEqual({
      subcommand: { kind: "format" },
      help: true,
    });
    expect(parseArgs(["-h"])).toEqual({
      subcommand: { kind: "format" },
      help: true,
    });
  });

  it("recognizes the status subcommand", () => {
    expect(parseArgs(["status"])).toEqual({ subcommand: { kind: "status" } });
  });

  it("status rejects trailing args", () => {
    expect(() => parseArgs(["status", "foo"])).toThrow(ArgsError);
  });

  it("recognizes the routes subcommand", () => {
    expect(parseArgs(["routes"])).toEqual({ subcommand: { kind: "routes" } });
  });

  it("routes rejects trailing args", () => {
    expect(() => parseArgs(["routes", "foo"])).toThrow(ArgsError);
  });

  it("models without a flag defaults to gateway (route=undefined)", () => {
    expect(parseArgs(["models"])).toEqual({
      subcommand: { kind: "models", route: undefined },
    });
  });

  it("models --route <slug> carries the slug through", () => {
    expect(parseArgs(["models", "--route", "chrono-llm"])).toEqual({
      subcommand: { kind: "models", route: "chrono-llm" },
    });
  });

  it("models --route without a value throws", () => {
    expect(() => parseArgs(["models", "--route"])).toThrow(ArgsError);
  });

  it("models rejects unknown flags", () => {
    expect(() => parseArgs(["models", "--bogus"])).toThrow(ArgsError);
  });

  it("config list", () => {
    expect(parseArgs(["config", "list"])).toEqual({
      subcommand: { kind: "config-list" },
    });
  });

  it("config get <key>", () => {
    expect(parseArgs(["config", "get", "model"])).toEqual({
      subcommand: { kind: "config-get", key: "model" },
    });
  });

  it("config set <key> <value> (kebab-case key is accepted)", () => {
    expect(parseArgs(["config", "set", "api-key", "sk-xyz"])).toEqual({
      subcommand: { kind: "config-set", key: "api_key", value: "sk-xyz" },
    });
  });

  it("config unset <key>", () => {
    expect(parseArgs(["config", "unset", "model"])).toEqual({
      subcommand: { kind: "config-unset", key: "model" },
    });
  });

  it("config set without value errors", () => {
    expect(() => parseArgs(["config", "set", "model"])).toThrow(ArgsError);
  });

  it("config with unknown action errors", () => {
    expect(() => parseArgs(["config", "foo"])).toThrow(ArgsError);
  });

  it("config with unknown key errors", () => {
    expect(() => parseArgs(["config", "get", "bogus"])).toThrow(ArgsError);
  });

  it("throws ArgsError when --in is missing a value", () => {
    expect(() => parseArgs(["--in"])).toThrow(ArgsError);
  });

  it("throws ArgsError when --in is followed by another flag", () => {
    expect(() => parseArgs(["--in", "--out", "x"])).toThrow(ArgsError);
  });

  it("throws ArgsError on unknown arg", () => {
    expect(() => parseArgs(["--bogus"])).toThrow(ArgsError);
  });
});

let server: ReturnType<typeof Bun.serve>;
let outDir: string;
let homeDir: string;

const FIXTURE_BRIEF = {
  content_type: "daily_brief_v1",
  spec_id: "executive-broadsheet",
  title: "CLI Smoke",
  summary: "Generated by the CLI test.",
  top_priorities: [],
  watchlist: [],
  timeline: [],
  notes: [],
};

beforeAll(() => {
  outDir = mkdtempSync(join(tmpdir(), "nocturne-cli-"));
  // Force HOME to an empty tmp dir so subprocess CLI invocations do NOT
  // accidentally read the user's real ~/.nyxid tokens and try to call the
  // real NyxID server.
  homeDir = mkdtempSync(join(tmpdir(), "nocturne-cli-home-"));
  server = Bun.serve({
    port: 0,
    fetch: async (req) => {
      expect(new URL(req.url).pathname).toBe("/v1/chat/completions");
      expect(req.headers.get("authorization")).toBe("Bearer sk-local-test");
      return new Response(
        JSON.stringify({
          choices: [{ message: { content: JSON.stringify(FIXTURE_BRIEF) } }],
        }),
        { status: 200, headers: { "content-type": "application/json" } },
      );
    },
  });
});

afterAll(() => {
  server.stop(true);
  rmSync(outDir, { recursive: true, force: true });
  rmSync(homeDir, { recursive: true, force: true });
});

describe("CLI: bun run src/cli/format.ts", () => {
  it("reads stdin, writes an HTML file, and prints the path", async () => {
    const proc = Bun.spawn({
      cmd: ["bun", "run", "src/cli/format.ts", "--out-dir", outDir],
      env: {
        ...process.env,
        HOME: homeDir,
        NOCTURNE_OPENAI_API_KEY: "sk-local-test",
        NOCTURNE_OPENAI_BASE_URL: `http://127.0.0.1:${server.port}/v1`,
        NOCTURNE_OPENAI_MODEL: "gpt-fixture",
        NOCTURNE_OUT_DIR: outDir,
      },
      stdin: new Response("Raw content for the CLI.").body ?? undefined,
      stdout: "pipe",
      stderr: "pipe",
    });
    const out = await new Response(proc.stdout).text();
    const err = await new Response(proc.stderr).text();
    const code = await proc.exited;

    expect(code).toBe(0);
    expect(err).toBe("");
    const printedPath = out.trim();
    expect(printedPath.startsWith(outDir)).toBe(true);
    expect(printedPath.endsWith(".html")).toBe(true);

    const html = readFileSync(printedPath, "utf8");
    expect(html).toContain("<!doctype html>");
    expect(html).toContain("CLI Smoke");

    const entries = readdirSync(outDir).filter((f) => f.endsWith(".html"));
    expect(entries.length).toBe(1);
  }, 15_000);

  it("fails with a helpful message when neither NyxID nor OpenAI is configured", async () => {
    const proc = Bun.spawn({
      cmd: ["bun", "run", "src/cli/format.ts"],
      env: {
        ...process.env,
        HOME: homeDir,
        NOCTURNE_OPENAI_API_KEY: "",
      },
      stdin: new Response("x").body ?? undefined,
      stdout: "pipe",
      stderr: "pipe",
    });
    const err = await new Response(proc.stderr).text();
    const code = await proc.exited;
    expect(code).not.toBe(0);
    expect(err).toContain("NOCTURNE_OPENAI_API_KEY");
    expect(err).toContain("nyxid login");
  }, 10_000);

  it("`config get language` round-trips the value", async () => {
    const isolatedHome = mkdtempSync(join(tmpdir(), "nocturne-get-lang-"));
    try {
      const env = { ...process.env, HOME: isolatedHome };
      // Set it.
      const setProc = Bun.spawn({
        cmd: ["bun", "run", "src/cli/format.ts", "config", "set", "language", "zh"],
        env,
        stdout: "pipe",
        stderr: "pipe",
      });
      expect(await setProc.exited).toBe(0);

      // Read it back.
      const getProc = Bun.spawn({
        cmd: ["bun", "run", "src/cli/format.ts", "config", "get", "language"],
        env,
        stdout: "pipe",
        stderr: "pipe",
      });
      const out = await new Response(getProc.stdout).text();
      const code = await getProc.exited;
      expect(code).toBe(0);
      expect(out.trim()).toBe("zh");
    } finally {
      rmSync(isolatedHome, { recursive: true, force: true });
    }
  }, 10_000);

  it("`config set language` rejects values outside the enum", async () => {
    const isolatedHome = mkdtempSync(join(tmpdir(), "nocturne-set-lang-bad-"));
    try {
      const env = { ...process.env, HOME: isolatedHome };
      const proc = Bun.spawn({
        cmd: ["bun", "run", "src/cli/format.ts", "config", "set", "language", "fr"],
        env,
        stdout: "pipe",
        stderr: "pipe",
      });
      const err = await new Response(proc.stderr).text();
      const code = await proc.exited;
      expect(code).not.toBe(0);
      expect(err).toContain("language");
      expect(err).toContain("en");
      expect(err).toContain("zh");
      // Critical: file must not have been written with the invalid value.
      // (If it had, the next CLI read would fail with a schema error, but
      // we assert the write was skipped entirely.)
      const cfgPath = join(isolatedHome, ".config", "nocturne", "config.json");
      let fileWritten = true;
      try {
        readFileSync(cfgPath, "utf8");
      } catch {
        fileWritten = false;
      }
      // The file should either not exist, OR not contain the invalid "fr".
      if (fileWritten) {
        const body = readFileSync(cfgPath, "utf8");
        expect(body).not.toContain('"fr"');
      }
    } finally {
      rmSync(isolatedHome, { recursive: true, force: true });
    }
  }, 10_000);

  it("`status` subcommand prints auth state without hitting the planner", async () => {
    const proc = Bun.spawn({
      cmd: ["bun", "run", "src/cli/format.ts", "status"],
      env: {
        ...process.env,
        HOME: homeDir,
        NOCTURNE_OPENAI_API_KEY: "",
      },
      // No stdin — status MUST NOT try to read the planner input.
      stdout: "pipe",
      stderr: "pipe",
    });
    const out = await new Response(proc.stdout).text();
    const code = await proc.exited;
    expect(code).toBe(0);
    expect(out).toContain("NyxID");
    expect(out).toContain("not logged in");
    expect(out).toContain("OpenAI API key");
    expect(out).toContain("not set");
  }, 10_000);

  it("`config set` then format uses the config-file values (no env vars)", async () => {
    // Use a fresh HOME so the config file and the (absent) ~/.nyxid are
    // both scoped to this test.
    const isolatedHome = mkdtempSync(join(tmpdir(), "nocturne-cfgset-"));
    try {
      const envBase: Record<string, string | undefined> = {
        ...process.env,
        HOME: isolatedHome,
      };
      // Wipe any real OPENAI key from the inherited env.
      delete envBase.NOCTURNE_OPENAI_API_KEY;
      delete envBase.NOCTURNE_OPENAI_MODEL;
      delete envBase.NOCTURNE_OPENAI_BASE_URL;
      delete envBase.NOCTURNE_OUT_DIR;

      // Write model / base-url / api-key through the CLI itself.
      for (const args of [
        ["config", "set", "model", "gpt-fixture"],
        ["config", "set", "base-url", `http://127.0.0.1:${server.port}/v1`],
        ["config", "set", "api-key", "sk-local-test"],
        ["config", "set", "out-dir", outDir],
      ]) {
        const proc = Bun.spawn({
          cmd: ["bun", "run", "src/cli/format.ts", ...args],
          env: envBase,
          stdout: "pipe",
          stderr: "pipe",
        });
        const code = await proc.exited;
        const err = await new Response(proc.stderr).text();
        expect({ args, code, err }).toEqual({ args, code: 0, err: "" });
      }

      // Run format with zero env vars — config file must supply everything.
      const proc = Bun.spawn({
        cmd: ["bun", "run", "src/cli/format.ts"],
        env: envBase,
        stdin: new Response("Config-file-driven test.").body ?? undefined,
        stdout: "pipe",
        stderr: "pipe",
      });
      const out = await new Response(proc.stdout).text();
      const err = await new Response(proc.stderr).text();
      const code = await proc.exited;
      expect(err).toBe("");
      expect(code).toBe(0);
      const printedPath = out.trim();
      expect(printedPath.startsWith(outDir)).toBe(true);

      const html = readFileSync(printedPath, "utf8");
      expect(html).toContain("CLI Smoke");
    } finally {
      rmSync(isolatedHome, { recursive: true, force: true });
    }
  }, 20_000);

  it("`config list` shows env / file / default sources", async () => {
    const isolatedHome = mkdtempSync(join(tmpdir(), "nocturne-cfglist-"));
    try {
      // First write a model via CLI (will land in the file).
      const write = Bun.spawn({
        cmd: [
          "bun",
          "run",
          "src/cli/format.ts",
          "config",
          "set",
          "model",
          "deepseek-chat",
        ],
        env: { ...process.env, HOME: isolatedHome },
        stdout: "pipe",
        stderr: "pipe",
      });
      await write.exited;

      // Now list with an env override on base_url.
      const list = Bun.spawn({
        cmd: ["bun", "run", "src/cli/format.ts", "config", "list"],
        env: {
          ...process.env,
          HOME: isolatedHome,
          NOCTURNE_OPENAI_BASE_URL: "https://override.example.com/v1",
        },
        stdout: "pipe",
        stderr: "pipe",
      });
      const out = await new Response(list.stdout).text();
      await list.exited;

      // model comes from config file, base_url from env override,
      // out_dir from default, api_key unset/default.
      expect(out).toMatch(/model\s+deepseek-chat\s+file/);
      expect(out).toMatch(
        /base_url\s+https:\/\/override\.example\.com\/v1\s+env/,
      );
      expect(out).toMatch(/out_dir\s+\.\/out\s+default/);
      expect(out).toMatch(/api_key\s+<unset>\s+default/);
    } finally {
      rmSync(isolatedHome, { recursive: true, force: true });
    }
  }, 10_000);
});
