import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { mkdtempSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { ArgsError, parseArgs } from "./format.ts";

describe("parseArgs", () => {
  it("returns empty Args for no argv", () => {
    expect(parseArgs([])).toEqual({});
  });

  it("parses --in, --out, --out-dir", () => {
    expect(parseArgs(["--in", "a.md", "--out", "b.html", "--out-dir", "x"]))
      .toEqual({ inPath: "a.md", outPath: "b.html", outDir: "x" });
  });

  it("flags help", () => {
    expect(parseArgs(["--help"])).toEqual({ help: true });
    expect(parseArgs(["-h"])).toEqual({ help: true });
  });

  it("recognizes the status subcommand", () => {
    expect(parseArgs(["status"])).toEqual({ subcommand: "status" });
  });

  it("only the FIRST positional is treated as a subcommand", () => {
    // An unknown second positional still errors — we don't silently swallow
    // it because a subcommand slot exists.
    expect(() => parseArgs(["status", "format"])).toThrow(ArgsError);
  });

  it("throws ArgsError when --in is missing a value", () => {
    expect(() => parseArgs(["--in"])).toThrow(ArgsError);
  });

  it("throws ArgsError when --in is followed by another flag", () => {
    expect(() => parseArgs(["--in", "--out", "x"])).toThrow(ArgsError);
  });

  it("throws ArgsError on unknown arg", () => {
    expect(() => parseArgs(["--bogus"])).toThrow(ArgsError);
  });
});

let server: ReturnType<typeof Bun.serve>;
let outDir: string;
let homeDir: string;

const FIXTURE_BRIEF = {
  content_type: "daily_brief_v1",
  spec_id: "executive-broadsheet",
  title: "CLI Smoke",
  summary: "Generated by the CLI test.",
  top_priorities: [],
  watchlist: [],
  timeline: [],
  notes: [],
};

beforeAll(() => {
  outDir = mkdtempSync(join(tmpdir(), "nocturne-cli-"));
  // Force HOME to an empty tmp dir so subprocess CLI invocations do NOT
  // accidentally read the user's real ~/.nyxid tokens and try to call the
  // real NyxID server.
  homeDir = mkdtempSync(join(tmpdir(), "nocturne-cli-home-"));
  server = Bun.serve({
    port: 0,
    fetch: async (req) => {
      expect(new URL(req.url).pathname).toBe("/v1/chat/completions");
      expect(req.headers.get("authorization")).toBe("Bearer sk-local-test");
      return new Response(
        JSON.stringify({
          choices: [{ message: { content: JSON.stringify(FIXTURE_BRIEF) } }],
        }),
        { status: 200, headers: { "content-type": "application/json" } },
      );
    },
  });
});

afterAll(() => {
  server.stop(true);
  rmSync(outDir, { recursive: true, force: true });
  rmSync(homeDir, { recursive: true, force: true });
});

describe("CLI: bun run src/cli/format.ts", () => {
  it("reads stdin, writes an HTML file, and prints the path", async () => {
    const proc = Bun.spawn({
      cmd: ["bun", "run", "src/cli/format.ts", "--out-dir", outDir],
      env: {
        ...process.env,
        HOME: homeDir,
        NOCTURNE_OPENAI_API_KEY: "sk-local-test",
        NOCTURNE_OPENAI_BASE_URL: `http://127.0.0.1:${server.port}/v1`,
        NOCTURNE_OPENAI_MODEL: "gpt-fixture",
        NOCTURNE_OUT_DIR: outDir,
      },
      stdin: new Response("Raw content for the CLI.").body ?? undefined,
      stdout: "pipe",
      stderr: "pipe",
    });
    const out = await new Response(proc.stdout).text();
    const err = await new Response(proc.stderr).text();
    const code = await proc.exited;

    expect(code).toBe(0);
    expect(err).toBe("");
    const printedPath = out.trim();
    expect(printedPath.startsWith(outDir)).toBe(true);
    expect(printedPath.endsWith(".html")).toBe(true);

    const html = readFileSync(printedPath, "utf8");
    expect(html).toContain("<!doctype html>");
    expect(html).toContain("CLI Smoke");

    const entries = readdirSync(outDir).filter((f) => f.endsWith(".html"));
    expect(entries.length).toBe(1);
  }, 15_000);

  it("fails with a helpful message when neither NyxID nor OpenAI is configured", async () => {
    const proc = Bun.spawn({
      cmd: ["bun", "run", "src/cli/format.ts"],
      env: {
        ...process.env,
        HOME: homeDir,
        NOCTURNE_OPENAI_API_KEY: "",
      },
      stdin: new Response("x").body ?? undefined,
      stdout: "pipe",
      stderr: "pipe",
    });
    const err = await new Response(proc.stderr).text();
    const code = await proc.exited;
    expect(code).not.toBe(0);
    expect(err).toContain("NOCTURNE_OPENAI_API_KEY");
    expect(err).toContain("nyxid login");
  }, 10_000);

  it("`status` subcommand prints auth state without hitting the planner", async () => {
    const proc = Bun.spawn({
      cmd: ["bun", "run", "src/cli/format.ts", "status"],
      env: {
        ...process.env,
        HOME: homeDir,
        NOCTURNE_OPENAI_API_KEY: "",
      },
      // No stdin — status MUST NOT try to read the planner input.
      stdout: "pipe",
      stderr: "pipe",
    });
    const out = await new Response(proc.stdout).text();
    const code = await proc.exited;
    expect(code).toBe(0);
    expect(out).toContain("NyxID");
    expect(out).toContain("not logged in");
    expect(out).toContain("OpenAI API key");
    expect(out).toContain("not set");
  }, 10_000);
});
