import { afterAll, beforeAll, describe, expect, it } from "bun:test";
import { mkdtempSync, readFileSync, readdirSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

let server: ReturnType<typeof Bun.serve>;
let outDir: string;

const FIXTURE_BRIEF = {
  content_type: "daily_brief_v1",
  spec_id: "executive-broadsheet",
  title: "CLI Smoke",
  summary: "Generated by the CLI test.",
  top_priorities: [],
  watchlist: [],
  timeline: [],
  notes: [],
};

beforeAll(() => {
  outDir = mkdtempSync(join(tmpdir(), "nocturne-cli-"));
  server = Bun.serve({
    port: 0,
    fetch: async (req) => {
      expect(new URL(req.url).pathname).toBe("/v1/chat/completions");
      expect(req.headers.get("authorization")).toBe("Bearer sk-local-test");
      return new Response(
        JSON.stringify({
          choices: [{ message: { content: JSON.stringify(FIXTURE_BRIEF) } }],
        }),
        { status: 200, headers: { "content-type": "application/json" } },
      );
    },
  });
});

afterAll(() => {
  server.stop(true);
  rmSync(outDir, { recursive: true, force: true });
});

describe("CLI: bun run src/cli/format.ts", () => {
  it("reads stdin, writes an HTML file, and prints the path", async () => {
    const proc = Bun.spawn({
      cmd: ["bun", "run", "src/cli/format.ts", "--out-dir", outDir],
      env: {
        ...process.env,
        NOCTURNE_OPENAI_API_KEY: "sk-local-test",
        NOCTURNE_OPENAI_BASE_URL: `http://127.0.0.1:${server.port}/v1`,
        NOCTURNE_OPENAI_MODEL: "gpt-fixture",
        NOCTURNE_OUT_DIR: outDir,
      },
      stdin: new Response("Raw content for the CLI.").body ?? undefined,
      stdout: "pipe",
      stderr: "pipe",
    });
    const out = await new Response(proc.stdout).text();
    const err = await new Response(proc.stderr).text();
    const code = await proc.exited;

    expect(code).toBe(0);
    expect(err).toBe("");
    const printedPath = out.trim();
    expect(printedPath.startsWith(outDir)).toBe(true);
    expect(printedPath.endsWith(".html")).toBe(true);

    const html = readFileSync(printedPath, "utf8");
    expect(html).toContain("<!doctype html>");
    expect(html).toContain("CLI Smoke");

    const entries = readdirSync(outDir).filter((f) => f.endsWith(".html"));
    expect(entries.length).toBe(1);
  }, 15_000);

  it("fails fast with a clear message when NOCTURNE_OPENAI_API_KEY is missing", async () => {
    const proc = Bun.spawn({
      cmd: ["bun", "run", "src/cli/format.ts"],
      env: { ...process.env, NOCTURNE_OPENAI_API_KEY: "" },
      stdin: new Response("x").body ?? undefined,
      stdout: "pipe",
      stderr: "pipe",
    });
    const err = await new Response(proc.stderr).text();
    const code = await proc.exited;
    expect(code).not.toBe(0);
    expect(err).toContain("NOCTURNE_OPENAI_API_KEY");
  }, 10_000);
});
